### ISSUE TITLE
Echantillon non représentatif de la normale climatique

### ISSUE THREAD

**Issue by a-vine** [HippieVibe/Babospedie#3]
Dans la partie [Étude du climat](https://github.com/HippieVibe/Babospedie/blob/main/choisir_ou_sinstaller/choix_de_la_region.rst#%C3%A9tude-du-climat), une moyenne sur 10 ans n'est pas un échantillon représentatif pour calculer la [normale climatique](https://fr.wikipedia.org/wiki/Normale_climatique) d'un lieu. A priori, il faut "une période uniforme et relativement longue comprenant au moins trois périodes consécutives de dix années". En effet, il peut y avoir des [anomalies climatiques](https://fr.wikipedia.org/wiki/Anomalie_climatique) de moyen/long terme.

**Comment by HippieVibe** [comment]
Done
